name: seleda_finance
description: Seleda Finance personal finance MVP with Clean Architecture
publish_to: 'none'
version: 0.1.0+1
environment:
  sdk: '>=3.2.0 <4.0.0'
  flutter: '>=3.16.0'
dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.6
  flutter_riverpod: ^2.4.9
  go_router: ^12.1.1
  drift: ^2.13.0
  drift_flutter: ^2.13.0
  path_provider: ^2.1.2
  path: ^1.9.0
  image_picker: ^1.0.7
  speech_to_text: ^6.3.0
  intl: ^0.19.0
  uuid: ^4.2.2
  collection: ^1.18.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  mocktail: ^1.0.2
  drift_dev: ^2.13.0
  build_runner: ^2.4.8
flutter:
  uses-material-design: true
  assets:
    - assets/
